[FIX] Added checking for Java on the system in `bin/elasticsearch`
When Java wasn't installed/available in the system, a confusing "permission denied" error
was diplayed to users:

    user@server:/home/ubuntu/elasticsearch-0.19.9# ./bin/elasticsearch -f
    ./bin/elasticsearch: 122: exec: : Permission denied

This patch fixes the issue by checking for:

a) Java script existence based on the $JAVA environment variable,
b) executability of the Java script

diff --git a/bin/elasticsearch b/bin/elasticsearch
--- a/bin/elasticsearch
+++ b/bin/elasticsearch
@@ -92,6 +92,11 @@ else
     JAVA=`which java`
 fi
 
+if [ -z $JAVA ] || [ ! -x $JAVA ]; then
+  echo "[!] Cannot find Java -- is it installed?"
+  exit 1
+fi
+
 if [ -z "$ES_CLASSPATH" ]; then
     echo "You must set the ES_CLASSPATH var" >&2
     exit 1
