Debian/Redhat package improvments
This decision helps people who want to rollout the oracle java without having an openjdk java installed.

* Removed any hard dependency on Java in the debian package
* The debian init script does not check for an existing JAVA_HOME anymore
* Debian and RedHat initscripts now exit if they do not find a java binary (instead of starting elasticsearch in the background and swallowing the error as there is no way to log it in that case)
* Changed the debian init script to rely on the pid file instead of the argument name of process
* Added a useful error message in case no java binary is available (in elasticsearch shell script)

Closes #3304
Closes #3311

diff --git a/bin/elasticsearch b/bin/elasticsearch
--- a/bin/elasticsearch
+++ b/bin/elasticsearch
@@ -89,7 +89,12 @@ fi
 if [ -x "$JAVA_HOME/bin/java" ]; then
     JAVA="$JAVA_HOME/bin/java"
 else
-    JAVA=java
+    JAVA=$(which java)
+fi
+
+if [ ! -x "$JAVA" ]; then
+    echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
+    exit 1
 fi
 
 if [ -z "$ES_CLASSPATH" ]; then
@@ -169,7 +174,7 @@ while true; do
             break
         ;;
         *)
-            echo "Error parsing arguments!" >&2
+            echo "Error parsing argument $1!" >&2
             exit 1
         ;;
     esac
