Honor gradle options for no Kibana builds+tests (elastic/elasticsearch#3448)
https://github.com/elastic/x-plugins/pull/3229 broke the possibility of
building+testing x-pack without Kibana via dev-tools/ci by setting an
option in ~/.gradle/gradle.properties as described in
https://github.com/dliappis/x-plugins/blob/master/README.asciidoc,
unless nvm is present.

Conditionally execute the nvm/nodejs code only if
`xpack.kibana.build=false` is not set in `~/.gradle/gradle.properties`

Original commit: elastic/x-pack-elasticsearch@affb4ac711a6da00f244d99e1cd989ac3525b433

diff --git a/dev-tools/ci b/dev-tools/ci
--- a/dev-tools/ci
+++ b/dev-tools/ci
@@ -5,8 +5,10 @@
 # unless the environment variable `USE_EXISTING_ES` has a value
 #
 # It will also attempt to install the appropriate version of node.js
-# for the Kibana plugin tests using nvm. Set a custom nvm directory
-# using the `NVM_DIR` environment variable.
+# for the Kibana plugin tests using nvm, unless
+# `xpack.kibana.build=false` is defined in
+# ~/.gradle/gradle.properties. Set a custom nvm directory using the
+# `NVM_DIR` environment variable.
 #
 
 # Turn on semi-strict mode
@@ -58,21 +60,24 @@ fi
 # back to base directory
 cd "$BASE_DIR"
 
-# install the correct node.js version
-if [ -z ${NVM_DIR:+x} ]; then
-  export NVM_DIR="/var/lib/jenkins/.nvm";
-fi
+if ! grep -q -e '^xpack\.kibana\.build=false$' ~/.gradle/gradle.properties
+then
+  # install the correct node.js version
+  if [ -z ${NVM_DIR:+x} ]; then
+    export NVM_DIR="/var/lib/jenkins/.nvm";
+  fi
 
-NVM_SCRIPT="$NVM_DIR/nvm.sh"
-if [ -s "$NVM_SCRIPT" ]; then
-  . "$NVM_SCRIPT"  # load nvm
-else
-  echo "Unable to find the nvm script at \"$NVM_SCRIPT\""
-  exit 1
-fi
+  NVM_SCRIPT="$NVM_DIR/nvm.sh"
+  if [ -s "$NVM_SCRIPT" ]; then
+    . "$NVM_SCRIPT"  # load nvm
+  else
+    echo "Unable to find the nvm script at \"$NVM_SCRIPT\""
+    exit 1
+  fi
 
-echo "Installing node.js version $(cat ./kibana/.node-version)..."
-nvm install "$(cat ./kibana/.node-version)"
+  echo "Installing node.js version $(cat ./kibana/.node-version)..."
+  nvm install "$(cat ./kibana/.node-version)"
+fi
 
 echo "Running X-Plugins tests..."
 echo "Running in $PWD"
