Fix exit code
Exit with proper exit code (1) and an error message if elasticsearch executable binary does not exists or has insufficient permissions to execute.

diff --git a/distribution/deb/src/main/packaging/init.d/elasticsearch b/distribution/deb/src/main/packaging/init.d/elasticsearch
--- a/distribution/deb/src/main/packaging/init.d/elasticsearch
+++ b/distribution/deb/src/main/packaging/init.d/elasticsearch
@@ -109,8 +109,10 @@ export ES_GC_LOG_FILE
 export JAVA_HOME
 export ES_INCLUDE
 
-# Check DAEMON exists
-test -x $DAEMON || exit 0
+if [ ! -x "$DAEMON" ] {
+	echo "Could not find elasticsearch executable binary."
+	exit 1
+}
 
 checkJava() {
 	if [ -x "$JAVA_HOME/bin/java" ]; then
