Elasticsearch: Rename plugin from 'xpack' to 'x-pack'
This is just to be consistent with out naming, which is
supposed to be `x-pack`.

Closes elastic/elasticsearch#1759

Original commit: elastic/x-pack-elasticsearch@0697f7085513eac564aa68af98b7f3edb1f36785

diff --git a/elasticsearch/x-pack/shield/bin/x-pack/syskeygen b/elasticsearch/x-pack/shield/bin/x-pack/syskeygen
--- a/elasticsearch/x-pack/shield/bin/x-pack/syskeygen
+++ b/elasticsearch/x-pack/shield/bin/x-pack/syskeygen
@@ -72,13 +72,17 @@ elif [ -f "/etc/default/elasticsearch" ]; then
    . "/etc/default/elasticsearch"
 fi
 
-# Parse any long getopt options and put them into properties
+# Parse any long getopt options and put them into properties before calling getopt below
+# Be dash compatible to make sure running under ubuntu works
 ARGCOUNT=$#
 COUNT=0
 while [ $COUNT -lt $ARGCOUNT ]
 do
     case $1 in
-      --*) properties="$properties $1 $2"
+      --*=*) properties="$properties -Des.${1#--}"
+           shift 1; COUNT=$(($COUNT+1))
+           ;;
+      --*) properties="$properties -Des.${1#--}=$2"
            shift ; shift; COUNT=$(($COUNT+2))
            ;;
       *) set -- "$@" "$1"; shift; COUNT=$(($COUNT+1))
@@ -90,9 +94,14 @@ if [ -e "$CONF_DIR" ]; then
     case "$properties" in
         *-Des.default.path.conf=*) ;;
         *)
+            if [ ! -d "$CONF_DIR/x-pack" ]; then
+                echo "ERROR: The configuration directory [$CONF_DIR/x-pack] does not exist. The syskeygen tool expects security configuration files in that location."
+                echo "The plugin may not have been installed with the correct configuration path. If [$ES_HOME/config/x-pack] exists, please copy the 'x-pack' directory to [$CONF_DIR]"
+                exit 1
+            fi
             properties="$properties -Des.default.path.conf=$CONF_DIR"
             ;;
-    esac
+        esac
 fi
 if [ -e "$CONF_FILE" ]; then
     case "$properties" in
@@ -105,8 +114,8 @@ fi
 
 export HOSTNAME=`hostname -s`
 
-# include watcher jars in classpath
-ES_CLASSPATH="$ES_CLASSPATH:$ES_HOME/plugins/xpack/*"
+# include shield jars in classpath
+ES_CLASSPATH="$ES_CLASSPATH:$ES_HOME/plugins/x-pack/*"
 
 # don't let JAVA_TOOL_OPTIONS slip in (e.g. crazy agents in ubuntu)
 # works around https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1441487
@@ -117,7 +126,7 @@ if [ "x$JAVA_TOOL_OPTIONS" != "x" ]; then
 fi
 
 cd "$ES_HOME" > /dev/null
-"$JAVA" $ES_JAVA_OPTS -cp "$ES_CLASSPATH" -Des.path.home="$ES_HOME" org.elasticsearch.watcher.trigger.schedule.tool.CronEvalTool "$@" $properties
+"$JAVA" $ES_JAVA_OPTS -cp "$ES_CLASSPATH" -Des.path.home="$ES_HOME" $properties org.elasticsearch.shield.crypto.tool.SystemKeyTool "$@"
 status=$?
 cd - > /dev/null
 exit $status
