Only support ubi-minimal and rename it ubi

diff --git a/distribution/docker/src/docker/Dockerfile b/distribution/docker/src/docker/Dockerfile
--- a/distribution/docker/src/docker/Dockerfile
+++ b/distribution/docker/src/docker/Dockerfile
@@ -18,18 +18,12 @@
 # Build stage 0 `builder`:
 # Extract Elasticsearch artifact
 ################################################################################
-${build_args}
 
 FROM ${base_image} AS builder
-<% if (variant == 'ubi_minimal') { %>
+<% if (variant == 'ubi') { %>
 # Install required packages to extract the Elasticsearch distribution
 RUN ${package_manager} install -y tar gzip
 <% } %>
-<% if (variant == 'ubi') { %>
-# `tini` is a tiny but valid init for containers. This is used to cleanly
-# control how ES and any child processes are shut down.
-COPY tini /tini
-<% } else { %>
 # `tini` is a tiny but valid init for containers. This is used to cleanly
 # control how ES and any child processes are shut down.
 #
@@ -37,7 +31,6 @@ COPY tini /tini
 # gpg, but the keyservers are slow to return the key and this can fail the
 # build. Instead, we check the binary against the published checksum.
 RUN set -eux ; \\
-    \\
     tini_bin="" ; \\
     case "\$(arch)" in \\
         aarch64) tini_bin='tini-arm64' ;; \\
@@ -48,8 +41,9 @@ RUN set -eux ; \\
     curl --retry 8 -S -L -O https://github.com/krallin/tini/releases/download/v0.19.0/\${tini_bin}.sha256sum ; \\
     sha256sum -c \${tini_bin}.sha256sum ; \\
     rm \${tini_bin}.sha256sum ; \\
-    mv \${tini_bin} /tini
-<% } %>
+    mv \${tini_bin} /tini ; \\
+    chmod +x /tini
+
 RUN mkdir /usr/share/elasticsearch
 WORKDIR /usr/share/elasticsearch
 
@@ -59,7 +53,7 @@ RUN tar zxf /opt/elasticsearch.tar.gz --strip-components=1
 RUN sed -i -e 's/ES_DISTRIBUTION_TYPE=tar/ES_DISTRIBUTION_TYPE=docker/' /usr/share/elasticsearch/bin/elasticsearch-env
 RUN mkdir -p config config/jvm.options.d data logs
 RUN chmod 0775 config config/jvm.options.d data logs
-COPY ${config_dir}/elasticsearch.yml ${config_dir}/log4j2.properties config/
+COPY config/elasticsearch.yml config/log4j2.properties config/
 RUN chmod 0660 config/elasticsearch.yml config/log4j2.properties
 
 ################################################################################
@@ -72,10 +66,14 @@ FROM ${base_image}
 
 ENV ELASTIC_CONTAINER true
 
-RUN ${package_manager} update --setopt=tsflags=nodocs -y && \\
-    ${package_manager} install --setopt=tsflags=nodocs -y \\
-      nc shadow-utils zip unzip <%= variant == 'ubi_minimal' ? 'findutils procps-ng' : '' %> && \\
-    ${package_manager} clean all
+RUN for iter in {1..10}; do \\
+      ${package_manager} update --setopt=tsflags=nodocs -y && \\
+      ${package_manager} install --setopt=tsflags=nodocs -y \\
+        nc shadow-utils zip unzip <%= variant == 'ubi' ? 'findutils procps-ng' : '' %> && \\
+      ${package_manager} clean all && exit_code=0 && break || exit_code=\$? && echo "${package_manager} error: retry \$iter in 10s" && \\
+      sleep 10; \\
+    done; \\
+    (exit \$exit_code)
 
 RUN groupadd -g 1000 elasticsearch && \\
     adduser -u 1000 -g 1000 -G 0 -d /usr/share/elasticsearch elasticsearch && \\
@@ -85,7 +83,6 @@ RUN groupadd -g 1000 elasticsearch && \\
 WORKDIR /usr/share/elasticsearch
 COPY --from=builder --chown=1000:0 /usr/share/elasticsearch /usr/share/elasticsearch
 COPY --from=builder --chown=0:0 /tini /tini
-RUN chmod +x /tini
 
 # Replace OpenJDK's built-in CA certificate keystore with the one from the OS
 # vendor. The latter is superior in several ways.
@@ -94,7 +91,8 @@ RUN ln -sf /etc/pki/ca-trust/extracted/java/cacerts /usr/share/elasticsearch/jdk
 
 ENV PATH /usr/share/elasticsearch/bin:\$PATH
 
-COPY ${bin_dir}/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
+COPY bin/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
+
 RUN chmod g=u /etc/passwd && \\
     chmod 0775 /usr/local/bin/docker-entrypoint.sh
 
@@ -128,9 +126,7 @@ USER elasticsearch:root
 ENTRYPOINT ["/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]
 # Dummy overridable parameter parsed by entrypoint
 CMD ["eswrapper"]
-<% if (variant == 'ubi') { %>
-HEALTHCHECK --interval=10s --timeout=5s --start-period=1m --retries=5 CMD curl -I -f --max-time 5 http://localhost:9200 || exit 1
-<% } %>
+
 ################################################################################
 # End of multi-stage Dockerfile
 ################################################################################
