Follow Docker guidelines and put script contents into Dockerfile

diff --git a/distribution/docker/src/docker/Dockerfile b/distribution/docker/src/docker/Dockerfile
--- a/distribution/docker/src/docker/Dockerfile
+++ b/distribution/docker/src/docker/Dockerfile
@@ -16,19 +16,134 @@
 # many dependencies.
 ################################################################################
 FROM alpine:latest AS curl
-COPY bin/build-curl.sh /
-RUN /build-curl.sh
 
+ENV VERSION 7.71.0
+ENV TARBALL_URL https://curl.haxx.se/download/curl-\${VERSION}.tar.xz
+ENV TARBALL_PATH curl-\${VERSION}.tar.xz
+
+# Install dependencies
+RUN apk add gnupg gcc make musl-dev openssl-dev openssl-libs-static file
+
+RUN mkdir /work
+WORKDIR /work
+
+# Fetch curl sources and files for validation
+RUN wget "https://daniel.haxx.se/mykey.asc" -O "curl-gpg.pub" && \\
+    wget "\${TARBALL_URL}.asc" -O "\${TARBALL_PATH}.asc" && \\
+    wget "\${TARBALL_URL}" -O "\${TARBALL_PATH}"
+
+# Validate source
+RUN gpg --import --always-trust "curl-gpg.pub" && \\
+    gpg --verify "\${TARBALL_PATH}.asc" "\${TARBALL_PATH}"
+
+# Unpack and build
+RUN tar xfJ "\${TARBALL_PATH}" && \\
+    cd "curl-\${VERSION}" && \\
+    ./configure --disable-shared --with-ca-fallback --with-ca-bundle=/etc/pki/tls/certs/ca-bundle.crt && \\
+    make curl_LDFLAGS="-all-static" && \\
+    cp src/curl /work/curl && \\
+    strip /work/curl
 
 ################################################################################
 # Step 2. Create a minimal root filesystem directory. This will form the basis
 # for our image.
 ################################################################################
 FROM centos:7 AS rootfs
-COPY bin/build-rootfs.sh /
-RUN /build-rootfs.sh /rootfs
-COPY --from=curl /work/curl /rootfs/usr/bin/curl
 
+ENV BUSYBOX_VERSION 1.31.0
+ENV TINI_VERSION 0.19.0
+
+# Start off with an up-to-date system
+RUN yum update --setopt=tsflags=nodocs -y
+
+# Create a directory into which we will install files
+RUN mkdir /rootfs
+
+# Create required devices
+RUN mkdir -m 755 /rootfs/dev && \\
+    mknod -m 600 /rootfs/dev/console c 5 1 && \\
+    mknod -m 600 /rootfs/dev/initctl p && \\
+    mknod -m 666 /rootfs/dev/full c 1 7 && \\
+    mknod -m 666 /rootfs/dev/null c 1 3 && \\
+    mknod -m 666 /rootfs/dev/ptmx c 5 2 && \\
+    mknod -m 666 /rootfs/dev/random c 1 8 && \\
+    mknod -m 666 /rootfs/dev/tty c 5 0 && \\
+    mknod -m 666 /rootfs/dev/tty0 c 4 0 && \\
+    mknod -m 666 /rootfs/dev/urandom c 1 9 && \\
+    mknod -m 666 /rootfs/dev/zero c 1 5
+
+# Install a minimal set of dependencies, and some for Elasticsearch
+RUN yum --installroot=/rootfs --releasever=/ --setopt=tsflags=nodocs \\
+      --setopt=group_package_types=mandatory -y  \\
+      --skip-broken \\
+      install \\
+        basesystem  bash  glibc  libstdc++  zip  zlib
+
+# The tini GitHub page gives instructions for verifying the binary using
+# gpg, but the keyservers are slow to return the key and this can fail the
+# build. Instead, we check the binary against the published checksum.
+#
+# Also, we use busybox instead of installing utility RPMs, which pulls in
+# all kinds of stuff we don't want.
+RUN set -e ; \\
+    TINI_BIN="" ; \\
+    BUSYBOX_ARCH="" ; \\
+    case "\$(arch)" in \\
+        aarch64) \\
+            BUSYBOX_ARCH='armv8l' ; \\
+            TINI_BIN='tini-arm64' ; \\
+            ;; \\
+        x86_64) \\
+            BUSYBOX_ARCH='x86_64' ; \\
+            TINI_BIN='tini-amd64' ; \\
+            ;; \\
+        *) echo >&2 "Unsupported architecture \$(arch)" ; exit 1 ;; \\
+    esac ; \\
+    curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/\${TINI_BIN}" ; \\
+    curl --retry 8 -S -L -O "https://github.com/krallin/tini/releases/download/v0.19.0/\${TINI_BIN}.sha256sum" ; \\
+    sha256sum -c "\${TINI_BIN}.sha256sum" ; \\
+    rm "\${TINI_BIN}.sha256sum" ; \\
+    mv "\${TINI_BIN}" /rootfs/bin/tini ; \\
+    chmod +x /rootfs/bin/tini ; \\
+    curl --retry 10 -L -o /rootfs/bin/busybox \\
+      "https://busybox.net/downloads/binaries/\${BUSYBOX_VERSION}-defconfig-multiarch-musl/busybox-\${BUSYBOX_ARCH}" ; \\
+    chmod +x /rootfs/bin/busybox
+
+# Add links for most of the Busybox utilities
+RUN set -e ; \\
+    for path in \$( /rootfs/bin/busybox --list-full | grep -v bin/sh | grep -v telnet ); do \\
+      ln /rootfs/bin/busybox /rootfs/\$path ; \\
+    done
+
+# Curl needs files under here. More importantly, we change Elasticsearch's
+# bundled JDK to use /etc/pki/ca-trust/extracted/java/cacerts instead of
+# the bundled cacerts.
+RUN mkdir -p /rootfs/etc && \\
+    cp -a /etc/pki /rootfs/etc/
+
+# Cleanup the filesystem
+RUN yum --installroot=/rootfs -y clean all && \\
+    cd /rootfs && \\
+    rm -rf \\
+        etc/{X11,centos-release*,csh*,profile*,skel*,yum*} \\
+        sbin/sln \\
+        usr/bin/rpm \\
+        {usr,var}/games \\
+        usr/lib/{dracut,systemd,udev} \\
+        usr/lib64/X11 \\
+        usr/local \\
+        usr/share/{awk,centos-release,cracklib,desktop-directories,gcc-*,i18n,icons,licenses,xsessions,zoneinfo} \\
+        usr/share/{man,doc,info,games,gdb,ghostscript,gnome,groff,icons,pixmaps,sounds,backgrounds,themes,X11} \\
+        usr/{{lib,share}/locale,{lib,lib64}/gconv,bin/localedef,sbin/build-locale-archive} \\
+        var/cache/yum \\
+        var/lib/{rpm,yum} \\
+        var/log/yum.log
+
+# ldconfig
+RUN rm -rf /rootfs/etc/ld.so.cache /rootfs/var/cache/ldconfig && \\
+    mkdir -p --mode=0755 /rootfs/var/cache/ldconfig
+
+COPY --from=curl /work/curl /rootfs/usr/bin/curl
 
 ################################################################################
 # Step 3. Fetch the Elasticsearch distribution and configure it for Docker
