Use keystore passphrase file only with systemd
Originally, the logic in the shell scripts for reading a passphrase from
a file was meant to support the systemd case, where it was not possible
to easily read in a password using standard input. It has been pointed
out that this is not a capability that needs to exposed in the Archive
distribution cases. If a user *wants* to use such a file, it should be
simple for them to script it into standard input for our shell scripts.

This PR moves the logic for getting the name of a passphrase file from
an environment variable to an "entrypoint" script that will be
distributed with package installations. Users can set the environment
variable using the systemctl set-environment command.

This simplifies our startup scripts and makes some of our keystore
management tests relevant only to Systemd environments.

diff --git a/distribution/src/bin/elasticsearch b/distribution/src/bin/elasticsearch
--- a/distribution/src/bin/elasticsearch
+++ b/distribution/src/bin/elasticsearch
@@ -27,17 +27,9 @@ KEYSTORE_PASSWORD=
 if ! echo $* | grep -E -q '(^-h |-h$| -h |--help$|--help |^-V |-V$| -V |--version$|--version )' \
     && "`dirname "$0"`"/elasticsearch-keystore has-passwd --silent
 then
-  if [ -e "$ES_KEYSTORE_PASSPHRASE_FILE" ] ; then
-    if ! read -s -r KEYSTORE_PASSWORD <"$ES_KEYSTORE_PASSPHRASE_FILE" ; then
-      echo "Failed to read passphrase from file: $ES_KEYSTORE_PASSPHRASE_FILE" 1>&2
-      exit 1
-    fi
-  else
-    if ! read -s -r -p "Elasticsearch keystore password: " KEYSTORE_PASSWORD ; then
-      echo "Failed to read keystore password on console" 1>&2
-      exit 1
-    fi
-    echo
+  if ! read -s -r -p "Elasticsearch keystore password: " KEYSTORE_PASSWORD ; then
+    echo "Failed to read keystore password on console" 1>&2
+    exit 1
   fi
 fi
 
