use similar structure for checking in windows and nix

diff --git a/distribution/src/bin/elasticsearch-env b/distribution/src/bin/elasticsearch-env
--- a/distribution/src/bin/elasticsearch-env
+++ b/distribution/src/bin/elasticsearch-env
@@ -38,11 +38,7 @@ ES_CLASSPATH="$ES_HOME/lib/*"
 # now set the path to java
 if [ ! -z "$JAVA_HOME" ]; then
   JAVA="$JAVA_HOME/bin/java"
-  if [ ! -x "$JAVA" ]; then
-    echo "could not find java in JAVA_HOME at $JAVA" >&2
-    exit 1
-  fi
-
+  JAVA_TYPE="JAVA_HOME"
 else
   if [ "$(uname -s)" = "Darwin" ]; then
     # OSX has a different structure
@@ -50,11 +46,13 @@ else
   else
     JAVA="$ES_HOME/jdk/bin/java"
   fi
-  if [ ! -x "$JAVA" ]; then
-    echo "could not find java in bundled jdk at $JAVA" >&2
+  JAVA_TYPE="bundled jdk"
+fi
+
+if [ ! -x "$JAVA" ]; then
+    echo "could not find java in $JAVA_TYPE at $JAVA" >&2
     exit 1
   fi
-fi
 
 # do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
 if [ ! -z "$JAVA_TOOL_OPTIONS" ]; then
