Clarify missing java error message
Since the bundled jdk was added to Elasticsearch, there are now 2 ways
java can be missing. Either JAVA_HOME is set but does not exist, or the
bundled jdk does not exist. This commit improves the error messages in
those two cases, and also ensures our tests cover both cases.

diff --git a/distribution/src/bin/elasticsearch-env b/distribution/src/bin/elasticsearch-env
--- a/distribution/src/bin/elasticsearch-env
+++ b/distribution/src/bin/elasticsearch-env
@@ -38,6 +38,11 @@ ES_CLASSPATH="$ES_HOME/lib/*"
 # now set the path to java
 if [ ! -z "$JAVA_HOME" ]; then
   JAVA="$JAVA_HOME/bin/java"
+  if [ ! -x "$JAVA" ]; then
+    echo "could not find java JAVA_HOME at $JAVA" >&2
+    exit 1
+  fi
+
 else
   if [ "$(uname -s)" = "Darwin" ]; then
     # OSX has a different structure
@@ -45,11 +50,10 @@ else
   else
     JAVA="$ES_HOME/jdk/bin/java"
   fi
-fi
-
-if [ ! -x "$JAVA" ]; then
-  echo "could not find java in JAVA_HOME or bundled at $JAVA" >&2
-  exit 1
+  if [ ! -x "$JAVA" ]; then
+    echo "could not find java in bundled jdk at $JAVA" >&2
+    exit 1
+  fi
 fi
 
 # do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
