Get Windows tests to pass
There was a very strange issue in our Windows tests due to the
interaction between CMD.exe and powershell. Powershell, as far as I can
tell, doesn't have any convenient "run in background" operator like a
Unix shell "&". To get a "daemonized" windows process running in the
background, we wrap our bin/elasticsearch.bat command in a powershell
Process object, redirect its standard output and error, and let it run.
Then our powershell script can exit while Elasticsearch keeps running on
Windows, and we can verify that it's up and running.

But it seems that when you redirect standard output away from CMD.exe,
something has to be reading that output, or else the batch script will
halt. My changes introduced a diagnostic message when reading the
keystore password from a file, so, on Windows, the elasticsearch.bat
script would halt there. Elasticsearch would never start. Once I removed
this message so that the first standard output comes from the
Elasticsearch startup command, the tests would pass.

There were also possiby some issues with password encoding that I
addressed on this ticket. Windows Batch may be so old that it expects
ASCII instead of UTF8 when reading variables from files. Or this might
have been a red herring on the way to figuring out the standard output
issue. I will do a little testing to follow up and see if my ASCII
changes are really necessary.

diff --git a/distribution/src/bin/elasticsearch b/distribution/src/bin/elasticsearch
--- a/distribution/src/bin/elasticsearch
+++ b/distribution/src/bin/elasticsearch
@@ -28,8 +28,10 @@ if ! echo $* | grep -E -q '(^-h |-h$| -h |--help$|--help |^-V |-V$| -V |--versio
     && "`dirname "$0"`"/elasticsearch-keystore has-passwd >/dev/null 2>&1
 then
   if [ -e "$ES_KEYSTORE_PASSPHRASE_FILE" ] ; then
-    echo "Reading keystore passphrase from file $ES_KEYSTORE_PASSPHRASE_FILE" 1>&2
-    read -s KEYSTORE_PASSWORD <"$ES_KEYSTORE_PASSPHRASE_FILE"
+    if ! read -s KEYSTORE_PASSWORD <"$ES_KEYSTORE_PASSPHRASE_FILE" ; then
+      echo "Failed to read passphrase from file: $ES_KEYSTORE_PASSPHRASE_FILE" 1>&2
+      exit 1
+    fi
   else
     # read from standard input
     if ! read -s -p "Elasticsearch keystore password: " KEYSTORE_PASSWORD ; then
