Improve bin/elasticsearch portability
It's convenient to use the bin/elasticsearch-keystore list command to
test whether or not the keystore is encrypted. When no password is
supplied to an encrypted keystore, the command has a non-zero exit
status. However, many JVMs on OSX with default networking configuration
will take at least five seconds to run an elasticsearch-keystore
command. This is because we have to initialize log4j 2, and that
initialization code will call InetAddress.getLocalHost().getHostname(),
which is the bit of code with the bug. Since all our OSX distributions
come in tarballs, I've parameterized bin/elasticsearch so that we check
the encrypted flag byte with "dd". It might be nice to do this just for
Darwin distributions. For RPMs and Debian distros, we use the keystore
tool for the check.

I've also added a little bit more output to the bin/elasticsearch
command, and improved handling of the case where the script fails to
read any lines from standard input.

diff --git a/distribution/src/bin/elasticsearch b/distribution/src/bin/elasticsearch
--- a/distribution/src/bin/elasticsearch
+++ b/distribution/src/bin/elasticsearch
@@ -30,18 +30,22 @@ KEYSTORE_PASSWORD=
 if [ -f "$ES_PATH_CONF"/elasticsearch.keystore ] \
     && ! echo $* | grep -E '(^-h |-h$| -h |--help$|--help )' >/dev/null 2>&1 \
     && ! echo $* | grep -E '(^-V |-V$| -V |--version$|--version )' >/dev/null 2>&1 \
-    && hexdump -b -s 31 -n1 "$ES_PATH_CONF"/elasticsearch.keystore | head -1 | cut -d' ' -f2 | grep '001' >/dev/null 2>&1
+    && ! ${keystore.passwd.check} >/dev/null 2>&1
 then
   if [ -e "$ES_KEYSTORE_PASSPHRASE_FILE" ] ; then
     # read from a file or a FIFO
     if [ -p "$ES_KEYSTORE_PASSPHRASE_FILE" ] ; then
-      echo "Reading keystore passphrase from FIFO (blocking operation)"
+      echo "Reading keystore passphrase from FIFO $ES_KEYSTORE_PASSPHRASE_FILE (blocking operation)" 1>&2
+    else
+      echo "Reading keystore passphrase from file $ES_KEYSTORE_PASSPHRASE_FILE" 1>&2
     fi
-  read -s KEYSTORE_PASSWORD <"$ES_KEYSTORE_PASSPHRASE_FILE"
+  read -s KEYSTORE_PASSWORD -u "$ES_KEYSTORE_PASSPHRASE_FILE"
   else
     # read from standard input
-    echo -n "Elasticsearch keystore password: "
-    read -s KEYSTORE_PASSWORD
+    if ! read -s -p "Elasticsearch keystore password: " KEYSTORE_PASSWORD ; then
+      echo "Failed to read keystore password on standard input" 1>&2
+      exit 1
+    fi
     echo
   fi
 fi
