More error handling

diff --git a/distribution/src/bin/elasticsearch b/distribution/src/bin/elasticsearch
--- a/distribution/src/bin/elasticsearch
+++ b/distribution/src/bin/elasticsearch
@@ -51,12 +51,16 @@ then
 fi
 
 if [[ $AUTO_CONFIG = true ]]; then
+  # ignore failures in auto-configuration
+  # it is possible that an auto-configuration failure can prevent the node from starting, but this is only the exceptional case
+  # most likely an auto-configuration failure will leave the configuration untouched, optionally printing a message
+  # if the error is unexpected, but the node will start as usual
   ES_MAIN_CLASS=org.elasticsearch.xpack.security.cli.AutoConfigInitialNode \
     ES_ADDITIONAL_SOURCES="x-pack-env;x-pack-security-env" \
     ES_ADDITIONAL_CLASSPATH_DIRECTORIES=lib/tools/security-cli \
     "$(dirname "$0")/elasticsearch-cli" \
     "$@" \
-    <<<"$KEYSTORE_PASSWORD"
+    <<<"$KEYSTORE_PASSWORD" || true
 fi
 
 # The JVM options parser produces the final JVM options to start Elasticsearch.
