Respond to PR feedback
This commit restores some provision around when we expect to be reading
from an interactive terminal versus when we expect non-tty input. In
particular, when we use the "-x" flag to add a setting to the keystore,
we don't delegate our input read to the terminal, and read from standard
input directly instead.  We do something similar in the Bootstrap class.
We also adjust the mocking strategy in tests to fit this change.

diff --git a/distribution/src/bin/elasticsearch b/distribution/src/bin/elasticsearch
--- a/distribution/src/bin/elasticsearch
+++ b/distribution/src/bin/elasticsearch
@@ -33,9 +33,8 @@ then
       exit 1
     fi
   else
-    # read from standard input
     if ! read -s -p "Elasticsearch keystore password: " KEYSTORE_PASSWORD ; then
-      echo "Failed to read keystore password on standard input" 1>&2
+      echo "Failed to read keystore password on console" 1>&2
       exit 1
     fi
     echo
