move java check

diff --git a/distribution/src/bin/elasticsearch-env b/distribution/src/bin/elasticsearch-env
--- a/distribution/src/bin/elasticsearch-env
+++ b/distribution/src/bin/elasticsearch-env
@@ -41,6 +41,11 @@ if [ ! -z "$ES_JAVA_HOME" ]; then
   JAVA="$ES_JAVA_HOME/bin/java"
   JAVA_TYPE="ES_JAVA_HOME"
 
+  if [ ! -x "$JAVA" ]; then
+    echo "could not find java in $JAVA_TYPE at $JAVA" >&2
+    exit 1
+  fi
+
   # check the user supplied jdk version
   "$JAVA" -cp "$ES_HOME/lib/java-version-checker/*" org.elasticsearch.tools.java_version_checker.JavaVersionChecker
 else
@@ -52,11 +57,6 @@ else
     JAVA="$ES_HOME/jdk/bin/java"
   fi
   JAVA_TYPE="bundled JDK"
-fi
-
-if [ ! -x "$JAVA" ]; then
-  echo "could not find java in $JAVA_TYPE at $JAVA" >&2
-  exit 1
 fi
 
 # do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
