certutil converted

diff --git a/distribution/src/bin/elasticsearch-cli b/distribution/src/bin/elasticsearch-cli
--- a/distribution/src/bin/elasticsearch-cli
+++ b/distribution/src/bin/elasticsearch-cli
@@ -2,32 +2,82 @@
 
 set -e -o pipefail
 
-source "`dirname "$0"`"/elasticsearch-env
+CDPATH=""
 
-IFS=';' read -r -a additional_sources <<< "$ES_ADDITIONAL_SOURCES"
-for additional_source in "${additional_sources[@]}"
-do
-  source "$ES_HOME"/bin/$additional_source
+SCRIPT="$0"
+
+# SCRIPT might be an arbitrarily deep series of symbolic links; loop until we
+# have the concrete path
+while [ -h "$SCRIPT" ] ; do
+  ls=`ls -ld "$SCRIPT"`
+  # Drop everything prior to ->
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    SCRIPT="$link"
+  else
+    SCRIPT=`dirname "$SCRIPT"`/"$link"
+  fi
 done
 
-IFS=';' read -r -a additional_classpath_directories <<< "$ES_ADDITIONAL_CLASSPATH_DIRECTORIES"
-for additional_classpath_directory in "${additional_classpath_directories[@]}"
-do
-  ES_CLASSPATH="$ES_CLASSPATH:$ES_HOME/$additional_classpath_directory/*"
-done
+# determine Elasticsearch home; to do this, we strip from the path until we find
+# bin, and then strip bin (there is an assumption here that there is no nested
+# directory under bin also named bin)
+ES_HOME=`dirname "$SCRIPT"`
 
-# use a small heap size for the CLI tools, and thus the serial collector to
-# avoid stealing many CPU cycles; a user can override by setting ES_JAVA_OPTS
-ES_JAVA_OPTS="-Xms4m -Xmx64m -XX:+UseSerialGC ${ES_JAVA_OPTS}"
+# now make ES_HOME absolute
+ES_HOME=`cd "$ES_HOME"; pwd`
+
+while [ "`basename "$ES_HOME"`" != "bin" ]; do
+  ES_HOME=`dirname "$ES_HOME"`
+done
+ES_HOME=`dirname "$ES_HOME"`
+cd $ES_HOME
+
+# now set the path to java
+if [ ! -z "$ES_JAVA_HOME" ]; then
+  JAVA="$ES_JAVA_HOME/bin/java"
+  JAVA_TYPE="ES_JAVA_HOME"
+else
+  # use the bundled JDK (default)
+  if [ "$(uname -s)" = "Darwin" ]; then
+    # macOS has a different structure
+    JAVA="$ES_HOME/jdk.app/Contents/Home/bin/java"
+  else
+    JAVA="$ES_HOME/jdk/bin/java"
+  fi
+  JAVA_TYPE="bundled JDK"
+fi
+
+if [ ! -x "$JAVA" ]; then
+  echo "could not find java in $JAVA_TYPE at $JAVA" >&2
+  exit 1
+fi
+
+# do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
+if [ ! -z "$JAVA_TOOL_OPTIONS" ]; then
+  echo "warning: ignoring JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
+  unset JAVA_TOOL_OPTIONS
+fi
+
+# warn that we are not observing the value of JAVA_HOME
+if [ ! -z "$JAVA_HOME" ]; then
+  echo "warning: ignoring JAVA_HOME=$JAVA_HOME; using $JAVA_TYPE" >&2
+fi
+
+@source.path.env@
+ES_DISTRIBUTION_FLAVOR=@es.distribution.flavor@
+ES_DISTRIBUTION_TYPE=@es.distribution.type@
+ES_BUNDLED_JDK=@es.bundled_jdk@
+LAUNCHER_CLASSPATH=$ES_HOME/lib/*:$ES_HOME/lib/launcher/*
 
 exec \
-  "$JAVA" \
-  "$XSHARE" \
-  $ES_JAVA_OPTS \
-  -Des.path.home="$ES_HOME" \
-  -Des.path.conf="$ES_PATH_CONF" \
-  -Des.distribution.flavor="$ES_DISTRIBUTION_FLAVOR" \
-  -Des.distribution.type="$ES_DISTRIBUTION_TYPE" \
-  -cp "$ES_CLASSPATH" \
-  "$ES_MAIN_CLASS" \
-  "$@"
+    "$JAVA" \
+    $LAUNCHER_JAVA_OPTS \
+    -Des.path.home="$ES_HOME" \
+    -Des.path.conf="$ES_PATH_CONF" \
+    -Des.distribution.flavor="$ES_DISTRIBUTION_FLAVOR" \
+    -Des.distribution.type="$ES_DISTRIBUTION_TYPE" \
+    -Des.bundled_jdk="$ES_BUNDLED_JDK" \
+    -cp "$LAUNCHER_CLASSPATH" \
+    org.elasticsearch.launcher.Launcher \
+    "$@"
